[toolchain]
anchor_version = "1.0.2"
solana_version = "3.1.14"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
async_vault = "14rwtLEnG2XCYSaNuA2Tv6xKzt88YcAtuiaxtD2usuzi"

[programs.localnet]
async_vault = "14rwtLEnG2XCYSaNuA2Tv6xKzt88YcAtuiaxtD2usuzi"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
